version: '3'
services:
  two:
    build: .
    ports:
      - "5002:5002"
    command: ["flask", "run", "--host=0.0.0.0", "--port=5002"]
  five:
    build: .
    ports:
      - "5005:5005"
    command: ["flask", "run", "--host=0.0.0.0", "--port=5005"]
