version: '3'
services:
  # port number determines sleep time (e.g.: 5001 is 1 second of sleep time)
  one:
    build: .
    ports:
      - "5001:5001"
    command: ["flask", "run", "--host=0.0.0.0", "--port=5001"]
  two:
    build: .
    ports:
      - "5002:5002"
    command: ["flask", "run", "--host=0.0.0.0", "--port=5002"]
  five:
    build: .
    ports:
      - "5005:5005"
    command: ["flask", "run", "--host=0.0.0.0", "--port=5005"]
